package com.mindtree.hotelApp.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.mindtree.hotelApp.model.Cart;

/**
* Generated by Spring Data Generator on 22/09/2021
*/
@Repository
public interface CartRepository extends JpaRepository<Cart, Integer> {
	
	List<Cart> findCartByCustomerUserId(int userId);
	
	@Modifying
	@Query(value = "insert into carts(user_id,menu_id,quantity) value(?1,?2,?3)",
			nativeQuery = true)
	void addItemToCart(int userId, int menuId, int quantity) ;
	
	List<Cart> findCartByCustomerUserIdAndMenuItemMenuId(int userId, int menuId);

}
